version: '3'

services:
  mysql-container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890
      MYSQL_DATABASE: mysql
      MYSQL_USER: han
      MYSQL_PASSWORD: 1234567890
    ports:
      - "3307:3306"

  spring-app:
    build:
      context: .
    depends_on:
      - mysql-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3307/your_database
      SPRING_DATASOURCE_USERNAME: han
      SPRING_DATASOURCE_PASSWORD: 1234567890
