version: '3'

services:
#  mysql-container:
#    image: mysql:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: 1234567890
#      MYSQL_DATABASE: reader_books_database
#      MYSQL_USER: han
#      MYSQL_PASSWORD: 1234567890
#    ports:
#      - "3307:3306"

  spring-app:
    build:
      context: .
    depends_on:
      - mysql-container
    ports:
      - "3307:3306"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3307/reader_books_database
      SPRING_DATASOURCE_USERNAME: han
      SPRING_DATASOURCE_PASSWORD: 1234567890

  mysql>   alter user 'han'@'192.168.65.1' identified by '1234567890';